[package]
name = "sage"
version = "0.1.0"
description = "sage - a fast, ergonomic terminal pager (inspired by most)"

[sources]
include = [
  "src/**/*.slk"
]

[build]
default_target = "sage"
profile = "release"
build_module = true
build_module_path = "build.slk"

[test]
command = "silk test --package ."

[[target]]
name = "sage"
kind = "executable"
entry = "src/main.slk"
output = "build/bin/sage"
